apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "customer_deployment.fullname" . }}-configmap
  labels:
    {{- include "customer_deployment.labels" . | nindent 4 }}
data:
  customer_name: {{ .Values.config.name }}
  customer_motto: {{ .Values.config.motto }}