apiVersion: v1
kind: Service
metadata:
  name: {{ include "customer_deployment.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{include "customer_deployment.fullname" .}}
