name: create_customer_app_local
on:
  issues:
    types: [labeled]

jobs:
  build: # Define a job named 'build'
    runs-on: ubuntu-latest # Specify the runner environment
    if: contains(github.event.issue.labels.*.name, 'create-customer')
    concurrency: 
      group: my-deployment-group
      cancel-in-progress: false 
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # pip install -r requirements.txt
        # github.event.issue.body
    - name: Update Customer Status
      run: python infra/update_status.py "deploying"
    - name: Run Python script
      run: python infra/deploy.py "${{ github.event.issue.body }}" "${{ secrets.API_KEY }}"
